import Head from 'next/head'
import Hero from './components/Hero'
import Instegram from './components/Instegram'
import Slider from './components/Slider'
import  SliderData  from './components/SliderData'

import Categery from './components/Categery'

export default function Home() {
  return (
    <div >
      <Head>
        <title>photography Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
      {/* components */}
      <Hero 
      heading='Capture Photogtaphy'
      message='I capture moment in nature and keep then alive.'
      />
      <Slider slides={SliderData} />
     <Instegram />
     <Categery />
    </div>
  )
}
